### ISSUE TITLE
Hand-code IV and regression derivatives in R so Python is unnecessary

### ISSUE THREAD

**Issue by rgiordan** [rgiordan/zaminfluence#1]

**Comment by grantmcdermott** [comment]
I mentioned this to Rachael the other day on Twitter, but might be useful to add here: 

Since autograd appears to be the primary reason for the Python dependency, I'd recommend taking a look at the new(ish) [torch](https://torch.mlverse.org/docs/index.html) implementation for R. This has direct bindings to the underlying libtorch C++ libraries, so no Python install required. The syntax is also pretty similar to the PyTorch implementation, which I'm sure you are familiar with.

More importantly, thanks for putting this package together! I still have to sit down and read the actual paper, but looks like it's going to be a big deal.

**Comment by rgiordan** [comment]
Thank you for the pointer!  I didn't know about that, and I agree, it might be a good way to go.

**Comment by rgiordan** [comment]
In case anyone else is watching this issue, my plan remains to get the IV and OLS derivatives implemented in R first since that's relatively easy (just a matter of finding the time at the moment).  I'll look into alternative autodiff frameworks a little later.

**Comment by rgiordan** [comment]
This is now done in https://github.com/rgiordan/zaminfluence/pull/11.  I'm going to make a new issue to look into Torch.
